battles/urls.py
from django.urls import path

from battles.views import *

app_name = "battles"
urlpatterns = [
    path('api/upload/', upload_battle, name='upload_battle'),
    path('<int:battle_id>/', view_battle, name='view_battle'),
    path('<int:battle_id>/opengraph/', battle_opengraph, name='battle_opengraph'),
    path('redir/<str:uploader_username>/latest/', redirect_to_user_latest_battle,
         name='redirect_to_user_latest_battle'),
    path('redir/<str:uploader_username>/<str:splatnet_id>/', redirect_from_splatnet_id,
         name='redirect_from_splatnet_id'),
    path('api/<int:battle_id>/json/', get_battle_json, name='get_battle_json'),
    path('api/<str:splatnet_id>/exists/', check_if_battle_exists, name='check_battle_exists'),
    path('api/recent/', get_recent_battle_ids, name='get_recent_battle_ids'),
    path('htmx/latest/', get_latest_battles, name='htmx_latest_battles'),
    path('global-data-export/', global_data_export, name='global_data_export'),
    path('global-data-export/redirect/', redirect_global_data_export, name='redirect_global_data_export'),
    path('groups/<int:group_id>/', view_battle_group, name='view_battle_group'),
    path('groups/<int:group_id>/opengraph/', battle_group_opengraph, name='battle_group_opengraph'),
    path('groups/create/', create_battle_group, name='create_battle_group'),
    path('groups/create/htmx/preview/', create_group_preview, name='create_group_preview')
]

splashcat/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps import views
from django.urls import path, include
from django.views.decorators.csrf import csrf_exempt
from strawberry.django.views import AsyncGraphQLView

import users.views as users_views
from battles.sitemaps import BattlesSitemap, BattleGroupsSitemap
from django.conf import settings

from indexnow.views import indexnow_api_key
from splashcat.oidc_provider_settings import openid_auth
from splashcat.schema import schema
from splashcat.sitemaps import StaticViewSitemap
from splashcat.views import home, sponsor, uploaders_information, health_check, robots_txt, legal, ads_txt, about
from users.sitemaps import UsersSitemap

sitemaps = {
    'static': StaticViewSitemap,
    'users': UsersSitemap,
    'battles': BattlesSitemap,
    'battle-groups': BattleGroupsSitemap,
}

urlpatterns = [
    path('', home, name='home'),
    path('graphql', csrf_exempt(openid_auth(AsyncGraphQLView.as_view(schema=schema, graphql_ide="apollo-sandbox")))),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
    path('unicorn/', include('django_unicorn.urls')),
    path('users/', include('users.urls')),
    path('groups/', include('groups.urls')),
    path('battles/', include('battles.urls')),
    path('videos/', include('videos.urls')),
    path('search/', include('search.urls')),
    path('assistant/', include('assistant.urls')),
    path('embeds/', include('embed_images.urls')),
    path('sponsors/', include('sponsors.urls')),
    path('@<str:username>/', users_views.profile, name='profile'),
    path('@<str:username>.json', users_views.profile_json, name='profile_json'),
    path('@<str:username>/battles/', users_views.profile_battle_list, name='profile_battles_list'),
    path('@<str:username>/album/', users_views.profile_album, name='profile_album'),
    path('@<str:username>/followers/', users_views.profile_follows, {'view_type': 'followers'}, name='profile_followers'),
    path('@<str:username>/following/', users_views.profile_follows, {'view_type': 'following'}, name='profile_following'),
    path('set_user_timezone/', users_views.set_user_timezone, name='set_user_timezone'),
    path('follow/<str:username>/', users_views.follow_user, name='follow_user'),
    path('unfollow/<str:username>/', users_views.unfollow_user, name='unfollow_user'),
    path('notifications/mark-read/', users_views.mark_notifications_as_read, name='mark_notifications_as_read'),
    path('notifications/fetch/', users_views.get_notifications, name='fetch_notifications'),
    path('sponsor/', sponsor, name='sponsor'),
    path('legal/', legal, name='legal'),
    path('about/', about, name='about'),
    path('uploaders-information/', uploaders_information, name='uploaders_information'),
    path('health-check/', health_check, name='health_check'),
    path('i18n/', include('django.conf.urls.i18n')),
    path('openid/', include('oidc_provider.urls', namespace='oidc_provider')),
    path('robots.txt', robots_txt, name='robots_txt'),
    path('ads.txt', ads_txt, name='ads_txt'),
    path(f'{settings.INDEXNOW_API_KEY}.txt', indexnow_api_key, name='indexnow_api_key'),
    # path('silk/', include('silk.urls', namespace='silk')),
    path(
        "sitemap.xml",
        views.index,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.index",
    ),
    path(
        "sitemap-<section>.xml",
        views.sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # let web server handle this in production
    urlpatterns += static('api/schemas/', document_root=settings.BASE_DIR / 'battles/format_schemas/')

sponsors/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy

from sponsors.views import *

app_name = "sponsors"
urlpatterns = [
    path('create-checkout-session/<str:price_id>/', create_checkout_session, name='create_checkout_session'),
    path('webhook/', webhook_received, name='webhook_received'),
    path('portal/', redirect_to_portal, name='redirect_to_portal'),
    path('success/', checkout_success, name='checkout_success'),
]

users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy

from users.forms import AuthenticationForm
from users.views import *

app_name = "users"
urlpatterns = [
    path('coral/friendcode/qr/<str:username>/', profile_qr_code, name='profile_qr_code'),
    path('opengraph/<str:username>/user/', profile_opengraph, name='profile_opengraph'),
    path('api/github-sponsors-webhook/', github_sponsors_webhook, name='github_sponsors_webhook'),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="users/login.html", form_class=AuthenticationForm),
        name="login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(),
        name="logout",
    ),
    path(
        "password-reset/",
        auth_views.PasswordResetView.as_view(
            template_name="users/password_reset/form.html",
            email_template_name="users/password_reset/email_content.txt",
            subject_template_name="users/password_reset/email_subject.txt",
            success_url=reverse_lazy("users:password_reset_done"),

        ),
        name="password_reset",
    ),
    path("password-reset/done/",
         auth_views.PasswordResetDoneView.as_view(template_name="users/password_reset/done.html"),
         name='password_reset_done'),
    path("password-reset/confirm/<uidb64>/<token>/",
         auth_views.PasswordResetConfirmView.as_view(template_name="users/password_reset/confirm.html",
                                                     success_url=reverse_lazy("users:password_reset_complete")),
         name='password_reset_confirm'),
    path("password-reset/complete/",
         auth_views.PasswordResetCompleteView.as_view(template_name="users/password_reset/complete.html"),
         name='password_reset_complete'),
    path(
        "register/",
        register,
        name="register",
    ),
    path(
        "settings/",
        user_settings,
        name="settings",
    ),
    path(
        "settings/request-data-export/",
        request_data_export,
        name="request_data_export",
    ),
    path('github/link/',
         link_github_account,
         name='link_github_account'),
    path('github/link/callback/',
         link_github_account_callback,
         name='link_github_account_callback'),
    path('api-keys/create/',
         create_api_key,
         name='create_api_key'),
    path('api-keys/<str:key>/delete/',
         delete_api_key,
         name='delete_api_key'),
    path('verify-email/<int:user_id>/<str:token>/',
         verify_email,
         name='verify_email'),
    path('verify-email/resend/',
         resend_verification_email,
         name='resend_verification_email'),
]

sponsors/models.py
from django.db import models

# Create your models here.

splashcat/views.py
import os

from django.conf import settings
from django.http import HttpResponse
from django.shortcuts import render

from announcements.models import Announcement
from battles.models import Battle
from users.models import User, Notification


def home(request):
    recent_battles = Battle.objects.with_prefetch() \
                         .prefetch_related('uploader__github_link') \
                         .select_related('vs_stage__name') \
                         .order_by('-uploaded_at')[:24]
    
    user_recent_battles = request.user.battles.with_prefetch().select_related('vs_stage__name') \
                              .order_by('-uploaded_at')[:12] if request.user.is_authenticated else None
    if request.user.is_authenticated:
        notifications = Notification.objects.filter(recipient=request.user, is_read=False).order_by('-created_at')
        timezone = request.user.timezone
    else:
        notifications = None
        timezone = None
    
    announcements = Announcement.objects.filter(active=True).order_by("-created_at")

    return render(request, 'splashcat/home.html', {
        'recent_battles': recent_battles,
        'user_recent_battles': user_recent_battles,
        'notifications': notifications,
        'user_local_timezone': timezone,
        'announcements': announcements,
    })



def sponsor(request):
    current_sponsors = User.objects.filter(github_link__is_sponsor=True, github_link__is_sponsor_public=True,
                                           github_link__sponsorship_amount_usd__gte=5) \
        .order_by('github_link__sponsorship_amount_usd').reverse()
    if settings.DEBUG:
        stripe_sponsors = User.objects.filter(stripe_customer_id__isnull=False)
    else:
        stripe_sponsors = User.objects.filter(_stripe_entitlements__contains="sponsor-badge")
    return render(request, 'splashcat/sponsor.html', {
        'current_sponsors': list(stripe_sponsors) + list(current_sponsors),
    })


def legal(request):
    return render(request, 'splashcat/legal.html')


def about(request):
    return render(request, 'splashcat/about.html')


def uploaders_information(request):
    developer_usernames = ["Joy", "catgirl"]
    developer_users = User.objects.filter(username__in=developer_usernames)

    developers = {}
    for user in developer_users:
        developers[user.username] = user

    return render(request, 'splashcat/uploaders_information.html', {
        'developers': developers,
    })


def health_check(request):
    return HttpResponse('okii :3')


def robots_txt(request):
    script_dir = os.path.dirname(__file__)
    abs_file_path = os.path.join(script_dir, 'robots.txt')
    with open(abs_file_path) as f:
        return HttpResponse(f.read(), content_type='text/plain', headers={'Cache-Control': 'public, max-age=86400'})


def ads_txt(request):
    script_dir = os.path.dirname(__file__)
    abs_file_path = os.path.join(script_dir, 'ads.txt')
    with open(abs_file_path) as f:
        return HttpResponse(f.read(), content_type='text/plain', headers={'Cache-Control': 'public, max-age=86400'})

sponsors/views.py
import json

import stripe
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponseServerError, HttpResponse, HttpResponseBadRequest
from django.views.decorators.http import require_POST

from users.models import User


# Create your views here.


@require_POST
@login_required
def create_checkout_session(request, price_id: str):
    if request.user.stripe_customer_id:
        customer_id = request.user.stripe_customer_id
    else:
        customer = stripe.Customer.create(
            email=request.user.email,
        )

        request.user.stripe_customer_id = customer.id
        request.user.save()

        customer_id = customer.id

    session = stripe.checkout.Session.create(
        line_items=[
            {
                # Provide the exact Price ID (for example, pr_1234) of the product you want to sell
                'price': price_id,
                'quantity': 1,
            },
        ],
        mode='subscription',
        client_reference_id="user-" + str(request.user.id),
        customer=customer_id,
        customer_update={
            "address": "auto",
            "name": "auto",
        },
        success_url='https://splashcat.ink/sponsors/success/?session_id={CHECKOUT_SESSION_ID}',
        cancel_url='https://splashcat.ink/sponsor/',
        automatic_tax={'enabled': True},
    )

    return redirect(session.url)


@require_POST
@csrf_exempt
def webhook_received(request):
    request_data = json.loads(request.body.decode())

    if settings.STRIPE_WEBHOOK_SECRET:
        # Retrieve the event by verifying the signature using the raw body and secret if webhook signing is configured.
        signature = request.headers.get('stripe-signature')
        try:
            event = stripe.Webhook.construct_event(
                payload=request_data, sig_header=signature, secret=settings.STRIPE_WEBHOOK_SECRET)
            data = event['data']
        except Exception as e:
            print(e)
            return HttpResponseServerError()
        # Get the type of webhook event sent - used to check the status of PaymentIntents.
        event_type = event['type']
    else:
        data = request_data['data']
        event_type = request_data['type']
    data_object = data['object']

    customer_id = data_object['customer']
    user = User.objects.get(stripe_customer_id=customer_id)

    if event_type == 'entitlements.active_entitlement_summary.updated':
        # Payment is successful and the subscription is created.
        # You should provision the subscription and save the customer ID to your database.
        print(data)
        entitlements = data_object['entitlements']['data']
        entitlements_list = [entitlement['lookup_key'] for entitlement in entitlements]

        user._stripe_entitlements = entitlements_list
        user.save()
    else:
        print('Unhandled event type {}'.format(event_type))

    return HttpResponse("ok")


@require_POST
@login_required
def redirect_to_portal(request):
    user: User = request.user
    if not user.stripe_customer_id:
        return HttpResponseBadRequest()
    session = stripe.billing_portal.Session.create(
        customer=user.stripe_customer_id,
        return_url="https://splashcat.ink/users/settings/",
    )
    return redirect(session.url)


def checkout_success(request):
    messages.success(request, 'Thank you for supporting Splashcat!')
    return redirect('home')

templates/splashcat/home.html
{% extends "base.html" %}
{% load static cache %}

{% block title %}Splashcat{% endblock %}

{% block content %}
    <h1 class="text-3xl font-splatoon1">
        Splashcat
    </h1>
    <p class="text-xl">An award-winning service to track Splatoon 3 battles</p>

    {% if announcements|length > 0 %}
        <div class="basis-1/2 flex justify-center items-center">
            {% include "splatnet_assets/squid_tape.html" with bg="bg-splatoon-purple -rotate-1 font-splatoon1 text-xl" content="Announcements" border="p-4" %}
        </div>
        <div class="flex flex-row gap-4 px-1 pb-2 items-center justify-center">
            {% for announcement in announcements %}
                <div class="group card-mask bg-gray-400 p-4 pt-2 rounded bg-contain bg-[url('../images/tapes-transparent.png')] max-w-fit odd:rotate-1 even:-rotate-1 hover:odd:rotate-2 hover:even:-rotate-2 hover:drop-shadow-2xl drop-shadow transition">
                    <img src="{% static 'images/tape/tape-1.png' %}?height=72" alt="" height="136" width="600"
                         class="group-odd:rotate-6 group-even:-rotate-6 drop-shadow mx-auto relative h-12 w-auto top-6 -mb-4">
                    <div class="flex flex-col justify-center items-center">
                        <h2 class="text-xl font-splatoon1 z-10">{{ announcement.title }}</h2>
                        <div>{{ announcement.content|safe }}</div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% endif %}

    {% if user.is_authenticated and user_recent_battles|length > 0 %}
        <h2 class="text-2xl font-splatoon1 mt-2">Your Recent Battles</h2>
        <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4">
            {% for battle in user_recent_battles %}
                {% include "users/includes/battle-card.html" with battle=battle %}
            {% endfor %}
        </div>
    {% else %}
        <div class="flex flex-col gap-4 px-1">
            <div class="flex flex-col md:flex-row gap-4">
                <div class="basis-1/2 card-mask -rotate-1 bg-gray-400 p-4 pt-2 rounded bg-contain bg-[url('../images/tapes-transparent.png')] mx-auto max-w-fit">
                    <img src="{% static 'images/tape/tape-1.png' %}?height=72" alt="" height="136" width="600"
                         class="rotate-6 drop-shadow z-10 mx-auto relative h-12 w-auto top-6">
                    <img src="{% static 'images/home/battles.png' %}?height=482" alt="battle cards"
                         class="drop-shadow-lg border-4 rounded border-gray-700 h-auto w-full mx-auto"
                         height="768" width="1542"
                         srcset="{% static 'images/home/battles.png' %}?width=400 400w,
                                 {% static 'images/home/battles.png' %}?width=500 500w,
                                 {% static 'images/home/battles.png' %}?width=600 600w,
                                 {% static 'images/home/battles.png' %}?width=700 700w,
                                 {% static 'images/home/battles.png' %}?width=716 716w,
                                 {% static 'images/home/battles.png' %}?width=1000 1000w,
                                 {% static 'images/home/battles.png' %} 1542w"
                         sizes="(min-width: 768px) 40vw, 90vw">
                </div>
                <div class="basis-1/2 flex justify-center items-center">
                    {% include "splatnet_assets/squid_tape.html" with bg="bg-splatoon-blue rotate-1 font-splatoon1 text-3xl" content="Track your battles!" border="p-4" %}
                </div>
            </div>

            <div class="flex flex-col md:flex-row-reverse gap-4">
                <div class="basis-1/2 card-mask rotate-1 bg-gray-400 p-4 pt-2 rounded bg-contain bg-[url('../images/tapes-transparent.png')] mx-auto max-w-fit overflow-hidden">
                    <img src="{% static 'images/tape/tape-2.png' %}?height=96" alt="" height="147" width="332"
                         class="-rotate-6 drop-shadow z-10 mx-auto relative h-16 w-auto top-6">
                    <img src="{% static 'images/home/statistics.png' %}" alt="a player's statistics"
                         class="drop-shadow-lg border-4 rounded border-gray-700 h-auto w-full mx-auto" height="274"
                         srcset="{% static 'images/home/statistics.png' %}?width=400 400w,
                                 {% static 'images/home/statistics.png' %}?width=500 500w,
                                 {% static 'images/home/statistics.png' %}?width=600 600w,
                                 {% static 'images/home/statistics.png' %}?width=700 700w,
                                 {% static 'images/home/statistics.png' %}?width=800 800w,
                                 {% static 'images/home/statistics.png' %} 900w"
                         sizes="(min-width: 768px) 40vw, 90vw"
                         width="900">
                    <img src="{% static 'images/tape/tape-1.png' %}?height=72" alt="" height="136" width="600"
                         class="relative z-10 drop-shadow h-10 w-auto bottom-8 left-[85%] -rotate-45">
                </div>
                <div class="basis-1/2 flex justify-center items-center">
                    {% include "splatnet_assets/squid_tape.html" with bg="bg-splatoon-purple -rotate-1 font-splatoon1 text-3xl" content="View battle statistics!" border="p-4" %}
                </div>
            </div>

            <div class="flex flex-col md:flex-row gap-4">
                <div class="flex flex-row justify-center items-center basis-1/3">
                    <img
                            src="{% static 'images/splashcat-sponsor-badge.png' %}?format=png" alt="sponsor badge"
                            height="16" width="16"
                            class="[image-rendering:pixelated] h-full w-auto min-h-[8rem] aspect-square">
                </div>
                <div class="basis-2/3 flex flex-col justify-center items-center gap-2">
                    {% include "splatnet_assets/squid_tape.html" with bg="bg-splatoon-purple rotate-1 font-splatoon1 text-3xl" content="Support Splashcat!" border="p-4" %}

                    <p class="max-w-lg text-lg text-center">
                        Sponsor Splashcat to support future development and receive a sponsor badge and profile
                        customizations!
                    </p>

                    <a href="{% url "sponsor" %}" class="p-4 bg-white text-black rounded text-lg"><img
                            src="{% static 'images/splashcat-sponsor-badge.png' %}?format=png" alt=""
                            class="h-8 w-8 inline [image-rendering:pixelated]"
                            height="16" width="16">
                        Sponsor</a>
                </div>
            </div>
        </div>
    {% endif %}

    <h2 class="text-2xl font-splatoon1 pt-8">Recent Battles</h2>
    <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4">
        {% for battle in recent_battles %}
            {% include "users/includes/battle-card.html" with battle=battle display_uploader=True use_random_color=True %}
        {% endfor %}
    </div>

    <h2 class="text-2xl font-splatoon1 pt-8">Data</h2>
    <div class="flex flex-row gap-4">
        <a href="{% url 'battles:global_data_export' %}" class="py-2 px-3 rounded bg-pink-700 hover:bg-pink-800">Global
            Battle
            Data</a>
    </div>

    <div id="timezone-holder" data-timezone="{{ user_local_timezone }}" hidden></div>
{% endblock %}

{% block js%}
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
            const userSavedTimezone = document.getElementById('timezone-holder').getAttribute('data-timezone');
        
        
            // JavaScript to capture user's timezone and store in UserProfile
            function setUserTimezone() {
                const userLocalTimezone = Intl.DateTimeFormat().resolvedOptions().timeZone;
                if (userLocalTimezone !== userSavedTimezone) {
                    fetch('set_user_timezone/', {
                        method: 'POST',
                        headers: {
                            'Content-Type': 'application/json',
                            'X-CSRFToken': csrftoken,
                        },
                        body: JSON.stringify({
                            'user_local_timezone': userLocalTimezone,
                        }) 
                    })
                    .then(response => response.json())
                    .then(data => {
                        if (data['updated']) {
                            location.reload();
                        }
                    })
                    .catch(error => {
                        console.error(error);
                    });        
                }
            };
        
            // Call the function to set the user's timezone
            if (csrftoken) {
                setUserTimezone();
            }
        
        });
    </script>
{% endblock %}

templates/splashcat/sponsor.html
{% extends "base.html" %}

{% load static %}

{% block title %}
    Sponsor
{% endblock %}

{% block content %}
    <h1 class="text-4xl">
        Heya!
    </h1>

    <p class="prose-xl max-w-prose prose-a:text-blue-500 prose-a:underline">
        Splashcat is developed primarily by <a href="{% url 'profile' 'catgirl' %}">Saige</a> (that's me!) with help
        from
        <a href="https://github.com/splashcat-ink">friends</a>. Please consider supporting my work by becoming a
        sponsor! Splashcat is expensive for me to host so it helps me so much.
        It would mean a lot to me!! You also get this cool little badge on your profile page!
    </p>

    <div class="text-lg py-2">
        <img src="{% static 'images/splashcat-sponsor-badge.png' %}?format=png" alt="Splashcat Sponsor"
             class="h-12 w-12 inline-block [image-rendering:pixelated]">
        <-- that's the cool badge!
    </div>

    <div class="text-sm">
        Payments are processed through <a href="https://stripe.com/" class="underline text-blue-500">Stripe</a>.
    </div>

    <div class="py-5">
        <h2 class="text-2xl font-splatoon1">Sponsor Features</h2>
        <ul class="list-disc list-inside text-lg max-w-prose">
            <li>
                Sponsor Badge
                <img src="{% static 'images/splashcat-sponsor-badge.png' %}?format=png" alt="Splashcat Sponsor"
                     class="h-8 w-8 inline-block [image-rendering:pixelated]">
                <p class="text-sm ml-8 text-gray-500">
                    Must configure GitHub sponsorship privacy as public to display.
                </p>
            </li>
            <li>
                Favorite Color
                <p class="text-md ml-8">
                    Set a favorite color to be used for sub and special weapon icons on your profile and elsewhere on
                    Splashcat.
                </p>
                <p class="text-sm ml-8 text-gray-500">
                    Sponsorship privacy does not affect this feature.
                </p>
            </li>
            <li>
                Page Backgrounds
                <p class="text-md ml-8">
                    Configure a background image to be shown on your profile and battle pages!
                </p>
                <p class="text-sm ml-8 text-gray-500">
                    Sponsorship privacy does not affect this feature.
                </p>
            </li>
        </ul>
        <div class="flex flex-row gap-2 pt-2">
            <form method="post" action="{% url 'sponsors:create_checkout_session' "price_1Oq6QeCJmzupkZn7tS58WNCG" %}">
                {% csrf_token %}
                <button type="submit" class="py-2 px-4 rounded bg-pink-600 hover:bg-pink-700">
                    $5/month
                </button>
            </form>
            <form method="post" action="{% url 'sponsors:create_checkout_session' "price_1Oq6SlCJmzupkZn745HUIbFJ" %}">
                {% csrf_token %}
                <button type="submit" class="py-2 px-4 rounded bg-pink-600 hover:bg-pink-700">
                    $50/year
                </button>
            </form>
        </div>
    </div>

    <div class="py-5">
        <h2 class="text-2xl font-splatoon1">S+ponsor Features</h2>
        <ul class="list-disc list-inside text-lg max-w-prose">
            <li>
                AI Battle Descriptions
                <p class="text-md ml-8">
                    Battles uploaded to Splashcat will have a short AI generated description added to them. Perfect for
                    sharing your battles on social media!
                </p>
                <p class="text-sm ml-8 text-gray-500">
                    Sponsorship privacy does not affect this feature.
                </p>
            </li>
            <li><span class="font-splatoon1">+</span> All Sponsor Features</li>
        </ul>
        <div class="flex flex-row gap-2 pt-2">
            <form method="post" action="{% url 'sponsors:create_checkout_session' "price_1Oq6TJCJmzupkZn7Zc0DIimS" %}">
                {% csrf_token %}
                <button type="submit" class="py-2 px-4 rounded bg-pink-600 hover:bg-pink-700">
                    $10/month
                </button>
            </form>
            <form method="post" action="{% url 'sponsors:create_checkout_session' "price_1Oq6TTCJmzupkZn7TcGChz6l" %}">
                {% csrf_token %}
                <button type="submit" class="py-2 px-4 rounded bg-pink-600 hover:bg-pink-700">
                    $100/year
                </button>
            </form>
        </div>
    </div>

    <div class="py-5">
        <h2 class="text-2xl font-splatoon1">Xponsor Features</h2>
        <ul class="list-disc list-inside text-lg max-w-prose">
            <li>
                Splashcat Assistant
                <p class="text-md ml-8">
                    Receive insights on your battle data and create new battle groups with Splashcat Assistant.
                    <a href="https://splashcat.ink/assistant/threads/shared/7a6226d0-083c-47af-97de-be2f20aca86c/"
                       class="text-blue-500 underline text-base">Example Thread</a>
                </p>
                <p class="text-sm ml-8 text-gray-500">
                    Sponsorship privacy does not affect this feature.
                </p>
            </li>
            <li><span class="font-splatoon1">+</span> All Sponsor and S+ponsor Features</li>
        </ul>

        <div class="flex flex-row gap-2 pt-2">
            <form method="post" action="{% url 'sponsors:create_checkout_session' "price_1Oq6UMCJmzupkZn7pwnBvGVG" %}">
                {% csrf_token %}
                <button type="submit" class="py-2 px-4 rounded bg-pink-600 hover:bg-pink-700">
                    $15/month
                </button>
            </form>
            <form method="post" action="{% url 'sponsors:create_checkout_session' "price_1Oq6UaCJmzupkZn7DRvUZR1l" %}">
                {% csrf_token %}
                <button type="submit" class="py-2 px-4 rounded bg-pink-600 hover:bg-pink-700">
                    $150/year
                </button>
            </form>
        </div>
    </div>

    <a href="https://climate.stripe.com/cLg3Ag" class="text-md py-2 font-semibold underline">
        <img src="{% static 'images/stripe-climate-badge.svg' %}" alt="Stripe Climate Badge"
             class="h-6 w-6 inline pr-1">
        Splashcat contributes 1% to remove CO<sub>2</sub> from the atmosphere.
    </a>

    {% if current_sponsors|length > 0 %}
        <h2 class="font-splatoon1 text-xl">Current Sponsors</h2>

        <div class="flex flex-row gap-2 flex-wrap">
            {% for sponsor in current_sponsors %}
                {% include "users/includes/user-link.html" with user=sponsor show_splashtag=True %}
            {% endfor %}
        </div>
    {% endif %}
{% endblock %}