assistant/urls.py
from django.urls import path

from assistant import views

app_name = "assistant"
urlpatterns = [
    path('threads/', views.threads, name='threads'),
    path('threads/<int:thread_id>/', views.view_thread, name='view_thread'),
    path('threads/shared/<str:shared_thread_id>/', views.view_shared_thread, name='view_shared_thread'),
    path('threads/<int:thread_id>/messages/', views.get_thread_messages, name='get_thread_messages'),
    path('threads/<int:thread_id>/messages/send/', views.send_message_to_thread, name='send_message_to_thread'),
    path('threads/<int:thread_id>/share/', views.share_thread, name='share_thread'),
    path('threads/create/', views.create_thread, name='create_thread'),
    path('threads/create/<str:app_label>/<str:model_name>/<int:object_id>/', views.create_thread, name='create_thread'),
]

splashcat/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps import views
from django.urls import path, include
from django.views.decorators.csrf import csrf_exempt
from strawberry.django.views import AsyncGraphQLView

import users.views as users_views
from battles.sitemaps import BattlesSitemap, BattleGroupsSitemap
from django.conf import settings

from indexnow.views import indexnow_api_key
from splashcat.oidc_provider_settings import openid_auth
from splashcat.schema import schema
from splashcat.sitemaps import StaticViewSitemap
from splashcat.views import home, sponsor, uploaders_information, health_check, robots_txt, legal, ads_txt, about
from users.sitemaps import UsersSitemap

sitemaps = {
    'static': StaticViewSitemap,
    'users': UsersSitemap,
    'battles': BattlesSitemap,
    'battle-groups': BattleGroupsSitemap,
}

urlpatterns = [
    path('', home, name='home'),
    path('graphql', csrf_exempt(openid_auth(AsyncGraphQLView.as_view(schema=schema, graphql_ide="apollo-sandbox")))),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
    path('unicorn/', include('django_unicorn.urls')),
    path('users/', include('users.urls')),
    path('groups/', include('groups.urls')),
    path('battles/', include('battles.urls')),
    path('videos/', include('videos.urls')),
    path('search/', include('search.urls')),
    path('assistant/', include('assistant.urls')),
    path('embeds/', include('embed_images.urls')),
    path('sponsors/', include('sponsors.urls')),
    path('@<str:username>/', users_views.profile, name='profile'),
    path('@<str:username>.json', users_views.profile_json, name='profile_json'),
    path('@<str:username>/battles/', users_views.profile_battle_list, name='profile_battles_list'),
    path('@<str:username>/album/', users_views.profile_album, name='profile_album'),
    path('@<str:username>/followers/', users_views.profile_follows, {'view_type': 'followers'}, name='profile_followers'),
    path('@<str:username>/following/', users_views.profile_follows, {'view_type': 'following'}, name='profile_following'),
    path('set_user_timezone/', users_views.set_user_timezone, name='set_user_timezone'),
    path('follow/<str:username>/', users_views.follow_user, name='follow_user'),
    path('unfollow/<str:username>/', users_views.unfollow_user, name='unfollow_user'),
    path('notifications/mark-read/', users_views.mark_notifications_as_read, name='mark_notifications_as_read'),
    path('notifications/fetch/', users_views.get_notifications, name='fetch_notifications'),
    path('sponsor/', sponsor, name='sponsor'),
    path('legal/', legal, name='legal'),
    path('about/', about, name='about'),
    path('uploaders-information/', uploaders_information, name='uploaders_information'),
    path('health-check/', health_check, name='health_check'),
    path('i18n/', include('django.conf.urls.i18n')),
    path('openid/', include('oidc_provider.urls', namespace='oidc_provider')),
    path('robots.txt', robots_txt, name='robots_txt'),
    path('ads.txt', ads_txt, name='ads_txt'),
    path(f'{settings.INDEXNOW_API_KEY}.txt', indexnow_api_key, name='indexnow_api_key'),
    # path('silk/', include('silk.urls', namespace='silk')),
    path(
        "sitemap.xml",
        views.index,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.index",
    ),
    path(
        "sitemap-<section>.xml",
        views.sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # let web server handle this in production
    urlpatterns += static('api/schemas/', document_root=settings.BASE_DIR / 'battles/format_schemas/')

users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy

from users.forms import AuthenticationForm
from users.views import *

app_name = "users"
urlpatterns = [
    path('coral/friendcode/qr/<str:username>/', profile_qr_code, name='profile_qr_code'),
    path('opengraph/<str:username>/user/', profile_opengraph, name='profile_opengraph'),
    path('api/github-sponsors-webhook/', github_sponsors_webhook, name='github_sponsors_webhook'),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="users/login.html", form_class=AuthenticationForm),
        name="login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(),
        name="logout",
    ),
    path(
        "password-reset/",
        auth_views.PasswordResetView.as_view(
            template_name="users/password_reset/form.html",
            email_template_name="users/password_reset/email_content.txt",
            subject_template_name="users/password_reset/email_subject.txt",
            success_url=reverse_lazy("users:password_reset_done"),

        ),
        name="password_reset",
    ),
    path("password-reset/done/",
         auth_views.PasswordResetDoneView.as_view(template_name="users/password_reset/done.html"),
         name='password_reset_done'),
    path("password-reset/confirm/<uidb64>/<token>/",
         auth_views.PasswordResetConfirmView.as_view(template_name="users/password_reset/confirm.html",
                                                     success_url=reverse_lazy("users:password_reset_complete")),
         name='password_reset_confirm'),
    path("password-reset/complete/",
         auth_views.PasswordResetCompleteView.as_view(template_name="users/password_reset/complete.html"),
         name='password_reset_complete'),
    path(
        "register/",
        register,
        name="register",
    ),
    path(
        "settings/",
        user_settings,
        name="settings",
    ),
    path(
        "settings/request-data-export/",
        request_data_export,
        name="request_data_export",
    ),
    path('github/link/',
         link_github_account,
         name='link_github_account'),
    path('github/link/callback/',
         link_github_account_callback,
         name='link_github_account_callback'),
    path('api-keys/create/',
         create_api_key,
         name='create_api_key'),
    path('api-keys/<str:key>/delete/',
         delete_api_key,
         name='delete_api_key'),
    path('verify-email/<int:user_id>/<str:token>/',
         verify_email,
         name='verify_email'),
    path('verify-email/resend/',
         resend_verification_email,
         name='resend_verification_email'),
]

assistant/models.py
import uuid
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.urls import reverse


# Create your models here.

class Thread(models.Model):
    class Status(models.TextChoices):
        PENDING = 'PENDING', 'Pending'
        CREATED = 'CREATED', 'Created'

    creator = models.ForeignKey('users.User', on_delete=models.CASCADE)
    openai_thread_id = models.CharField(max_length=255)
    openai_file_id = models.CharField(max_length=255, blank=True)
    created_date = models.DateTimeField(auto_now_add=True)
    initial_message = models.TextField(default='')
    status = models.CharField(blank=True, choices=Status.choices, max_length=25)
    runner_machine_id = models.CharField(blank=True, max_length=20)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE, blank=True, null=True)
    object_id = models.PositiveIntegerField(blank=True, null=True)
    content_object = GenericForeignKey("content_type", "object_id")

    class Meta:
        indexes = [
            models.Index(fields=["content_type", "object_id"]),
        ]

    def get_absolute_url(self):
        return reverse('assistant:view_thread', args=[str(self.id)])

    def __str__(self):
        return f"Thread {self.id} - {self.openai_thread_id} - @{self.creator.username}"


class SharedThread(models.Model):
    uuid = models.UUIDField(default=uuid.uuid4, editable=False, db_index=True, unique=True)
    creator = models.ForeignKey('users.User', on_delete=models.CASCADE)
    thread = models.ForeignKey(Thread, on_delete=models.CASCADE)
    data = models.JSONField()

    def get_absolute_url(self):
        return reverse('assistant:view_shared_thread', args=[str(self.uuid)])

assistant/forms.py
from django import forms


class CreateThreadForm(forms.Form):
    initial_message = forms.CharField(widget=forms.Textarea())

assistant/views.py
# Create your views here.
import json

import django_htmx.http
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.contenttypes.models import ContentType
from django.db import transaction
from django.http import HttpResponseBadRequest, HttpResponseNotFound
from django.shortcuts import redirect, get_object_or_404, render
from django.views.decorators.http import require_POST
from openai import OpenAI

from assistant import orchestrator, functions
from assistant.forms import CreateThreadForm
from assistant.models import Thread, SharedThread
from battles.models import Battle, BattleGroup
from users.models import User, SponsorshipTiers

client = OpenAI(api_key=settings.OPENAI_API_KEY)


def require_sponsor_tier(view_func):
    def _wrapper(request, *args, **kwargs):
        user: User = request.user
        if "assistant" not in user.entitlements:
            return redirect('sponsor')
        return view_func(request, *args, **kwargs)

    return _wrapper


@login_required
@require_sponsor_tier
def threads(request):
    user_threads = request.user.thread_set.order_by('-created_date')

    return render(request, "assistant/list_threads.html", {
        'threads': user_threads,
    })


@login_required
@require_sponsor_tier
@transaction.atomic
def create_thread(request, app_label=None, model_name=None, object_id=None):
    found_object: None = None
    if app_label:
        if not model_name and not object_id:
            return HttpResponseNotFound()
        content_type = ContentType.objects.get(app_label__iexact=app_label, model__iexact=model_name)
        found_object = content_type.get_object_for_this_type(pk=object_id)

        if content_type.model_class() is Battle:
            found_object: Battle
            if found_object.uploader_id != request.user.id:
                return HttpResponseBadRequest()
        elif content_type.model_class() is BattleGroup:
            found_object: BattleGroup
            if found_object.creator_id != request.user.id:
                return HttpResponseBadRequest()
        else:
            return HttpResponseBadRequest()

    if request.method == "GET":
        form = CreateThreadForm()
        return render(request, "assistant/create_thread.html", {
            'form': form,
        })

    form = CreateThreadForm(request.POST)
    if not form.is_valid():
        return HttpResponseBadRequest("Invalid create thread form.")

    openai_thread = client.beta.threads.create()
    thread = Thread(creator=request.user, openai_thread_id=openai_thread.id, status=Thread.Status.PENDING,
                    initial_message=form.cleaned_data['initial_message'])
    if found_object:
        thread.content_object = found_object
    thread.save()

    machine_id = orchestrator.schedule_machine(thread)

    thread.runner_machine_id = machine_id
    thread.save()

    return redirect("assistant:view_thread", thread.id)


@login_required
@require_sponsor_tier
def view_thread(request, thread_id):
    if request.user.is_superuser:
        thread = get_object_or_404(Thread, id=thread_id)
    else:
        thread = get_object_or_404(Thread, id=thread_id, creator=request.user)
    openai_thread_id = thread.openai_thread_id
    openai_thread_messages = client.beta.threads.messages.list(openai_thread_id, order='asc', limit=100)

    return render(request, "assistant/view_thread.html", {
        'thread': thread,
        'thread_messages': openai_thread_messages,
    })


@login_required
@require_sponsor_tier
def get_thread_messages(request, thread_id):
    thread = get_object_or_404(Thread, id=thread_id, creator=request.user)
    openai_thread_id = thread.openai_thread_id
    openai_thread_messages = client.beta.threads.messages.list(openai_thread_id, order='asc', limit=100)

    latest_run = client.beta.threads.runs.list(
        thread_id=openai_thread_id,
        limit=1,
        order='desc',
    )
    latest_run = latest_run.data[0] if len(latest_run.data) > 0 else None
    latest_status = latest_run.status if latest_run else 'completed'

    if latest_status == 'requires_action' and latest_run.required_action:
        # need to call functions
        outputs = []

        required_action = latest_run.required_action
        tools = required_action.submit_tool_outputs.tool_calls
        for tool in tools:
            function_name = tool.function.name
            python_function = getattr(functions, function_name)
            if python_function:
                result = python_function(thread.creator, params=json.loads(tool.function.arguments))
                outputs.append({
                    'tool_call_id': tool.id,
                    'output': str(result),
                })

        latest_run = client.beta.threads.runs.submit_tool_outputs(thread_id=openai_thread_id, run_id=latest_run.id,
                                                                  tool_outputs=outputs)

    is_currently_done = latest_status in ['completed', 'expired', 'cancelled',
                                          'failed'] and thread.status != thread.Status.PENDING

    is_disabling_input = request.GET.get('isDisablingInput', 'False') == 'True'
    if is_disabling_input == is_currently_done:
        response = render(request, "assistant/htmx/thread_container.html",
                          {'thread': thread, 'thread_messages': openai_thread_messages,
                           'message_sending_disabled': not is_currently_done, })

        django_htmx.http.retarget(response, '#entire-thread-container')
        # noinspection PyTypeChecker
        # morph:innerHTML is allowed, just part of an extension
        django_htmx.http.reswap(response, 'morph:innerHTML')

        return response

    return render(request, "assistant/htmx/messages_list.html", {
        'thread': thread,
        'thread_messages': openai_thread_messages,
        'message_sending_disabled': not is_currently_done,
        'gpt_processing': not is_currently_done,
    })


@login_required
@require_sponsor_tier
@require_POST
def send_message_to_thread(request, thread_id):
    thread = get_object_or_404(Thread, id=thread_id, creator=request.user)
    openai_thread_id = thread.openai_thread_id
    message = request.POST.get('message')

    client.beta.threads.messages.create(
        thread_id=openai_thread_id,
        content=message,
        role='user',
    )

    run = client.beta.threads.runs.create(
        thread_id=openai_thread_id,
        assistant_id=settings.OPENAI_ASSISTANT_ID,
    )

    openai_thread_messages = client.beta.threads.messages.list(openai_thread_id, order='asc', limit=100)

    return render(request, "assistant/htmx/thread_container.html", {
        'thread': thread,
        'thread_messages': openai_thread_messages,
        'message_sending_disabled': True,
        'gpt_processing': True,
    })


@login_required
@require_sponsor_tier
@require_POST
def share_thread(request, thread_id):
    if request.user.is_superuser:
        thread = get_object_or_404(Thread, id=thread_id)
    else:
        thread = get_object_or_404(Thread, id=thread_id, creator=request.user)
    new_shared_thread = SharedThread(creator=request.user, thread=thread)
    openai_thread_id = thread.openai_thread_id
    openai_thread_messages = client.beta.threads.messages.list(openai_thread_id, order='asc', limit=100)
    new_shared_thread.data = openai_thread_messages.to_dict()['data']
    new_shared_thread.save()

    return render(request, "assistant/htmx/share_result.html", {
        'shared_thread': new_shared_thread,
    })


def view_shared_thread(request, shared_thread_id):
    thread = get_object_or_404(SharedThread, uuid=shared_thread_id)

    return render(request, "assistant/view_shared_thread.html", {
        'thread': thread,
        'thread_messages': thread.data,
    })

assistant/templates/assistant/htmx/messages_list.html
{% load openai %}
{% load static %}
{% load markdownify %}
<div class="flex flex-col gap-2" hx-get="{% url 'assistant:get_thread_messages' thread.id %}"
     hx-trigger="every 5s" hx-swap="morph:outerHTML" id="messages-list" hx-indicator="#htmx-request-indicator"
     hx-vals='{"isDisablingInput": "{{ message_sending_disabled }}"}'>
    {% for message in thread_messages %}
        <div class="w-full rounded bg-gray-800/90 p-4 flex flex-row gap-2 overflow-x-auto">
            <div class="w-1/12 flex-none">
                {% if message.role == 'assistant' %}
                    <img src="{% static 'images/judd-pride.png' %}?optimizer=image&height=128&width=128"
                         alt="Splashcat Assistant"
                         class="h-16 w-16 object-cover rounded-lg aspect-square bg-gray-700"
                         height="128" width="128">
                {% else %}
                    {% if user.profile_picture %}
                        <img src="{{ user.profile_picture.url }}?optimizer=image&height=128&width=128"
                             alt="{{ user.display_name }}"
                             class="h-16 w-16 object-cover rounded-lg aspect-square bg-gray-700"
                             height="128" width="128">
                    {% endif %}
                {% endif %}
            </div>
            {% if message.role == 'assistant' %}
                <div class="prose prose-invert max-w-none grow">
                    {% for content in message.content %}
                        {% if content.type == 'text' %}
                            {{ content.text.value|markdownify }}
                        {% elif content.type == 'image_file' %}
                            <div class="max-w-xl">
                                {% get_openai_image content.image_file %}
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
            {% else %}
                <div class="grow">{{ message.content.0.text.value }}</div>
            {% endif %}
        </div>
    {% endfor %}

    {% if gpt_processing or thread.status == thread.Status.PENDING %}
        <div class="w-full rounded bg-gray-800/90 p-4 flex flex-row gap-2 overflow-x-auto">
            <div class="w-1/12 flex-none">
                <img src="{% static 'images/judd-pride.png' %}?optimizer=image&height=128&width=128"
                     alt="Splashcat Assistant"
                     class="h-16 w-16 object-cover rounded-lg aspect-square bg-gray-700"
                     height="128" width="128">
            </div>
            <div class="flex justify-center py-2 w-full">
                {% include "splatnet_assets/squid_spinner.html" with class="h-20 w-20 animate-[spin_2s_linear_infinite]" %}
            </div>
        </div>
    {% endif %}
</div>

assistant/templates/assistant/htmx/share_result.html
Your shared link has been created! <a class="text-blue-500 underline"
                                      href="{% url 'assistant:view_shared_thread' shared_thread.uuid %}">https://splashcat.ink{% url 'assistant:view_shared_thread' shared_thread.uuid %}</a>

<button class="share-button inline-block"
        data-url="https://splashcat.ink{% url 'assistant:view_shared_thread' shared_thread.uuid %}"
        data-content-type="SharedThread"
        data-share-type="webShare"
>
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
         stroke="currentColor" class="w-8 h-8 inline">
        <path stroke-linecap="round" stroke-linejoin="round"
              d="M9 8.25H7.5a2.25 2.25 0 00-2.25 2.25v9a2.25 2.25 0 002.25 2.25h9a2.25 2.25 0 002.25-2.25v-9a2.25 2.25 0 00-2.25-2.25H15m0-3l-3-3m0 0l-3 3m3-3V15"></path>
    </svg>
</button>

<button class="share-button inline-block"
        data-url="https://splashcat.ink{% url 'assistant:view_shared_thread' shared_thread.uuid %}"
        data-content-type="SharedThread"
        data-share-type="clipboard"
>
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-8 h-8 inline">
        <path fill-rule="evenodd"
              d="M19.902 4.098a3.75 3.75 0 00-5.304 0l-4.5 4.5a3.75 3.75 0 001.035 6.037.75.75 0 01-.646 1.353 5.25 5.25 0 01-1.449-8.45l4.5-4.5a5.25 5.25 0 117.424 7.424l-1.757 1.757a.75.75 0 11-1.06-1.06l1.757-1.757a3.75 3.75 0 000-5.304zm-7.389 4.267a.75.75 0 011-.353 5.25 5.25 0 011.449 8.45l-4.5 4.5a5.25 5.25 0 11-7.424-7.424l1.757-1.757a.75.75 0 111.06 1.06l-1.757 1.757a3.75 3.75 0 105.304 5.304l4.5-4.5a3.75 3.75 0 00-1.035-6.037.75.75 0 01-.354-1z"
              clip-rule="evenodd"></path>
    </svg>
</button>

<script>
	// get the two share buttons and call initShareButton() on each
	document.querySelectorAll('.share-button').forEach(window.initShareButton);
</script>

assistant/templates/assistant/htmx/thread_container.html
<div hx-get="{% url 'assistant:get_thread_messages' thread.id %}" hx-trigger="load"
     hx-vals='{"isDisablingInput": "{{ message_sending_disabled }}"}' hx-indicator="#htmx-request-indicator">
    {% include 'assistant/htmx/messages_list.html' %}
</div>

<div class="flex flex-row justify-start items-center gap-1 transition-opacity mr-4 htmx-indicator text-sm"
     id="htmx-request-indicator">
    {% include "splatnet_assets/squid_spinner.html" with class="h-6 w-6 animate-[spin_2s_linear_infinite]" %}
    Refreshing messages...
</div>

<form class="flex flex-row gap-4 form-css" hx-target="#entire-thread-container" hx-swap="innerHTML"
      hx-ext="loading-states" data-loading-states
      hx-post="{% url 'assistant:send_message_to_thread' thread.id %}" hx-trigger="submit throttle:5s"
      id="send-message-form">
    <label for="send-message-input" class="hidden" style="display: none;">Send a message...</label>
    <textarea name="message" id="send-message-input" rows="3" class="w-full grow placeholder:text-slate-200" data-loading-disable placeholder="shift+enter to send..."
              {% if message_sending_disabled %}disabled{% endif %} hx-on="keypress: window.keyUp(event)"></textarea>
    <input type="submit" value="Send" class="shrink text-xl min-w-fit" data-loading-disable
           {% if message_sending_disabled %}disabled{% endif %}>
</form>