assistant/urls.py
from django.urls import path

from assistant import views

app_name = "assistant"
urlpatterns = [
    path('threads/', views.threads, name='threads'),
    path('threads/<int:thread_id>/', views.view_thread, name='view_thread'),
    path('threads/shared/<str:shared_thread_id>/', views.view_shared_thread, name='view_shared_thread'),
    path('threads/<int:thread_id>/messages/', views.get_thread_messages, name='get_thread_messages'),
    path('threads/<int:thread_id>/messages/send/', views.send_message_to_thread, name='send_message_to_thread'),
    path('threads/<int:thread_id>/share/', views.share_thread, name='share_thread'),
    path('threads/create/', views.create_thread, name='create_thread'),
    path('threads/create/<str:app_label>/<str:model_name>/<int:object_id>/', views.create_thread, name='create_thread'),
]

battles/urls.py
from django.urls import path

from battles.views import *

app_name = "battles"
urlpatterns = [
    path('api/upload/', upload_battle, name='upload_battle'),
    path('<int:battle_id>/', view_battle, name='view_battle'),
    path('<int:battle_id>/opengraph/', battle_opengraph, name='battle_opengraph'),
    path('redir/<str:uploader_username>/latest/', redirect_to_user_latest_battle,
         name='redirect_to_user_latest_battle'),
    path('redir/<str:uploader_username>/<str:splatnet_id>/', redirect_from_splatnet_id,
         name='redirect_from_splatnet_id'),
    path('api/<int:battle_id>/json/', get_battle_json, name='get_battle_json'),
    path('api/<str:splatnet_id>/exists/', check_if_battle_exists, name='check_battle_exists'),
    path('api/recent/', get_recent_battle_ids, name='get_recent_battle_ids'),
    path('htmx/latest/', get_latest_battles, name='htmx_latest_battles'),
    path('global-data-export/', global_data_export, name='global_data_export'),
    path('global-data-export/redirect/', redirect_global_data_export, name='redirect_global_data_export'),
    path('groups/<int:group_id>/', view_battle_group, name='view_battle_group'),
    path('groups/<int:group_id>/opengraph/', battle_group_opengraph, name='battle_group_opengraph'),
    path('groups/create/', create_battle_group, name='create_battle_group'),
    path('groups/create/htmx/preview/', create_group_preview, name='create_group_preview')
]

groups/urls.py
from django.urls import path

from groups.views import view_group, groups_index, group_admin, answer_join_request, invite_to_group, \
    answer_group_invite, request_join_group, join_group, leave_group, create_group, delete_group

app_name = "groups"
urlpatterns = [
    path("", groups_index, name="index"),
    path("<int:group_id>/", view_group, name="view_group"),
    path("<int:group_id>/admin/", group_admin, name="group_admin"),
    path("<int:group_id>/admin/delete/", delete_group, name="delete_group"),
    path("create/", create_group, name="create_group"),
    path("<int:group_id>/request/", request_join_group, name="request_join_group"),
    path("<int:group_id>/request/answer/", answer_join_request, name="answer_join_request"),
    path("<int:group_id>/invite/", invite_to_group, name="invite_to_group"),
    path("<int:group_id>/invite/answer/", answer_group_invite, name="answer_group_invite"),
    path("<int:group_id>/join/", join_group, name="join_group"),
    path("<int:group_id>/leave/", leave_group, name="leave_group"),
]

splashcat/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps import views
from django.urls import path, include
from django.views.decorators.csrf import csrf_exempt
from strawberry.django.views import AsyncGraphQLView

import users.views as users_views
from battles.sitemaps import BattlesSitemap, BattleGroupsSitemap
from django.conf import settings

from indexnow.views import indexnow_api_key
from splashcat.oidc_provider_settings import openid_auth
from splashcat.schema import schema
from splashcat.sitemaps import StaticViewSitemap
from splashcat.views import home, sponsor, uploaders_information, health_check, robots_txt, legal, ads_txt, about
from users.sitemaps import UsersSitemap

sitemaps = {
    'static': StaticViewSitemap,
    'users': UsersSitemap,
    'battles': BattlesSitemap,
    'battle-groups': BattleGroupsSitemap,
}

urlpatterns = [
    path('', home, name='home'),
    path('graphql', csrf_exempt(openid_auth(AsyncGraphQLView.as_view(schema=schema, graphql_ide="apollo-sandbox")))),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
    path('unicorn/', include('django_unicorn.urls')),
    path('users/', include('users.urls')),
    path('groups/', include('groups.urls')),
    path('battles/', include('battles.urls')),
    path('videos/', include('videos.urls')),
    path('search/', include('search.urls')),
    path('assistant/', include('assistant.urls')),
    path('embeds/', include('embed_images.urls')),
    path('sponsors/', include('sponsors.urls')),
    path('@<str:username>/', users_views.profile, name='profile'),
    path('@<str:username>.json', users_views.profile_json, name='profile_json'),
    path('@<str:username>/battles/', users_views.profile_battle_list, name='profile_battles_list'),
    path('@<str:username>/album/', users_views.profile_album, name='profile_album'),
    path('@<str:username>/followers/', users_views.profile_follows, {'view_type': 'followers'}, name='profile_followers'),
    path('@<str:username>/following/', users_views.profile_follows, {'view_type': 'following'}, name='profile_following'),
    path('set_user_timezone/', users_views.set_user_timezone, name='set_user_timezone'),
    path('follow/<str:username>/', users_views.follow_user, name='follow_user'),
    path('unfollow/<str:username>/', users_views.unfollow_user, name='unfollow_user'),
    path('notifications/mark-read/', users_views.mark_notifications_as_read, name='mark_notifications_as_read'),
    path('notifications/fetch/', users_views.get_notifications, name='fetch_notifications'),
    path('sponsor/', sponsor, name='sponsor'),
    path('legal/', legal, name='legal'),
    path('about/', about, name='about'),
    path('uploaders-information/', uploaders_information, name='uploaders_information'),
    path('health-check/', health_check, name='health_check'),
    path('i18n/', include('django.conf.urls.i18n')),
    path('openid/', include('oidc_provider.urls', namespace='oidc_provider')),
    path('robots.txt', robots_txt, name='robots_txt'),
    path('ads.txt', ads_txt, name='ads_txt'),
    path(f'{settings.INDEXNOW_API_KEY}.txt', indexnow_api_key, name='indexnow_api_key'),
    # path('silk/', include('silk.urls', namespace='silk')),
    path(
        "sitemap.xml",
        views.index,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.index",
    ),
    path(
        "sitemap-<section>.xml",
        views.sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # let web server handle this in production
    urlpatterns += static('api/schemas/', document_root=settings.BASE_DIR / 'battles/format_schemas/')

users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy

from users.forms import AuthenticationForm
from users.views import *

app_name = "users"
urlpatterns = [
    path('coral/friendcode/qr/<str:username>/', profile_qr_code, name='profile_qr_code'),
    path('opengraph/<str:username>/user/', profile_opengraph, name='profile_opengraph'),
    path('api/github-sponsors-webhook/', github_sponsors_webhook, name='github_sponsors_webhook'),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="users/login.html", form_class=AuthenticationForm),
        name="login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(),
        name="logout",
    ),
    path(
        "password-reset/",
        auth_views.PasswordResetView.as_view(
            template_name="users/password_reset/form.html",
            email_template_name="users/password_reset/email_content.txt",
            subject_template_name="users/password_reset/email_subject.txt",
            success_url=reverse_lazy("users:password_reset_done"),

        ),
        name="password_reset",
    ),
    path("password-reset/done/",
         auth_views.PasswordResetDoneView.as_view(template_name="users/password_reset/done.html"),
         name='password_reset_done'),
    path("password-reset/confirm/<uidb64>/<token>/",
         auth_views.PasswordResetConfirmView.as_view(template_name="users/password_reset/confirm.html",
                                                     success_url=reverse_lazy("users:password_reset_complete")),
         name='password_reset_confirm'),
    path("password-reset/complete/",
         auth_views.PasswordResetCompleteView.as_view(template_name="users/password_reset/complete.html"),
         name='password_reset_complete'),
    path(
        "register/",
        register,
        name="register",
    ),
    path(
        "settings/",
        user_settings,
        name="settings",
    ),
    path(
        "settings/request-data-export/",
        request_data_export,
        name="request_data_export",
    ),
    path('github/link/',
         link_github_account,
         name='link_github_account'),
    path('github/link/callback/',
         link_github_account_callback,
         name='link_github_account_callback'),
    path('api-keys/create/',
         create_api_key,
         name='create_api_key'),
    path('api-keys/<str:key>/delete/',
         delete_api_key,
         name='delete_api_key'),
    path('verify-email/<int:user_id>/<str:token>/',
         verify_email,
         name='verify_email'),
    path('verify-email/resend/',
         resend_verification_email,
         name='resend_verification_email'),
]

groups/views.py
from django.contrib import messages
from django.http import HttpResponseForbidden
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.views.decorators.http import require_POST
from django_htmx.http import HttpResponseClientRedirect

from battles.models import Battle
from groups.forms import GroupAdminForm, GroupInviteForm
from groups.models import Group, Membership
from users.models import User


# Create your views here.

def groups_index(request):
    # discovery of new groups and links to joined groups
    user: User = request.user
    member_groups = user.get_groups() if user.is_authenticated else None
    if user.is_authenticated:
        random_public_groups = Group.objects.filter(privacy_level = Group.PrivacyLevels.PUBLIC).exclude(owner=user).exclude(members=user).order_by('?')[:24]
    else:
        random_public_groups = Group.objects.filter(privacy_level=Group.PrivacyLevels.PUBLIC).order_by('?')[:24]
    pending_invites = user.pending_group_invites.all() if user.is_authenticated else None
    return render(request, 'groups/index.html', {
        'member_groups': member_groups,
        'random_public_groups': random_public_groups,
        'pending_invites': pending_invites,
    })


def view_group(request, group_id):
    group = get_object_or_404(Group, pk=group_id)
    group_all_members = list(group.members.all()) + [group.owner]
    group_recent_battles = Battle.objects.with_card_prefetch().filter(uploader__in=group_all_members).order_by(
        "-played_time")[:16]
    is_group_member = request.user.is_authenticated and request.user in group_all_members

    battles = Battle.objects.filter(uploader__in=group_all_members)

    win_count = battles.filter(judgement='WIN').count()
    lose_count = battles.filter(judgement__in=['LOSE', 'DEEMED_LOSE']).count()
    win_rate = win_count / (win_count + lose_count) * 100 if win_count + lose_count else 0

    return render(request, 'groups/view.html', {
        'group': group,
        'group_recent_battles': group_recent_battles,
        'is_group_member': is_group_member,
        'win_count': win_count,
        'lose_count': lose_count,
        'win_rate': win_rate,
    })


def group_admin(request, group_id):
    group = get_object_or_404(Group, pk=group_id)
    if group.owner != request.user:
        return HttpResponseForbidden()
    if request.method == 'POST':
        form = GroupAdminForm(request.POST, request.FILES, instance=group)
        if form.is_valid():
            form.save()
            messages.success(request, 'Group settings updated.')
            return redirect('groups:view_group', group_id=group_id)
    else:
        form = GroupAdminForm(instance=group)
    group_invite_form = GroupInviteForm()
    return render(request, 'groups/admin/index.html', {
        'group': group,
        'form': form,
        'group_invite_form': group_invite_form,
    })


def create_group(request):
    if request.method == 'POST':
        form = GroupAdminForm(request.POST, request.FILES)
        if form.is_valid():
            group = form.save(commit=False)
            group.owner = request.user
            group.save()
            messages.success(request, 'Group created! Invite some friends to join.')
            return redirect('groups:view_group', group_id=group.pk)
    else:
        form = GroupAdminForm()
    return render(request, 'groups/admin/create.html', {
        'form': form,
    })


@require_POST
def request_join_group(request, group_id):
    group = get_object_or_404(Group, pk=group_id)
    if request.user in group.members.all():
        messages.error(request, 'You are already a member of this group.')
    elif request.user in group.pending_join_requests.all():
        messages.error(request, 'You already have a pending request to join this group.')
    else:
        group.pending_join_requests.add(request.user)
        messages.success(request, 'Request to join group sent.')
    return redirect('groups:view_group', group_id=group_id)


@require_POST
def answer_join_request(request, group_id):
    group = get_object_or_404(Group, pk=group_id)
    if group.owner != request.user:
        return HttpResponseForbidden()
    answer = request.POST.get('answer')
    split_string = answer.split(';')
    user_id = split_string[0]
    answer = split_string[1]
    user = get_object_or_404(User, pk=user_id)
    if answer == 'accept':
        group.pending_join_requests.remove(user)
        membership = Membership(
            person=user,
            group=group,
        )
        membership.save()
        messages.success(request, f'Accepted {user.username} into the group.')
    elif answer == 'deny':
        group.pending_join_requests.remove(user)
        messages.success(request, f'Rejected {user.username} from the group.')
    return redirect('groups:group_admin', group_id=group_id)


@require_POST
def invite_to_group(request, group_id):
    group = get_object_or_404(Group, pk=group_id)
    if group.owner != request.user:
        return HttpResponseForbidden()
    form = GroupInviteForm(request.POST)
    if form.is_valid():
        username = form.cleaned_data['username']
        user = get_object_or_404(User, username__iexact=username)
        if user in group.members.all():
            messages.error(request, f'{username} is already a member of the group.')
        elif user in group.pending_invites.all():
            messages.error(request, f'{username} already has a pending invite.')
        else:
            group.pending_invites.add(user)
            messages.success(request, f'Invited {username} to the group.')
    return redirect('groups:group_admin', group_id=group_id)


@require_POST
def answer_group_invite(request, group_id):
    group = get_object_or_404(Group, pk=group_id)
    user: User = request.user
    answer = request.POST.get('answer')
    if answer == 'accept':
        group.pending_invites.remove(user)
        membership = Membership(
            person=user,
            group=group,
        )
        membership.save()
        messages.success(request, f'Accepted invite to {group.name}.')
    elif answer == 'deny':
        group.pending_invites.remove(user)
        messages.success(request, f'Rejected invite to {group.name}.')
    return redirect('groups:index')


@require_POST
def join_group(request, group_id):
    group = get_object_or_404(Group, pk=group_id)
    if request.user in group.members.all():
        messages.error(request, 'You are already a member of this group.')
    else:
        membership = Membership(
            person=request.user,
            group=group,
        )
        membership.save()
        messages.success(request, f'Joined {group.name}.')
    return redirect('groups:view_group', group_id=group_id)


@require_POST
def leave_group(request, group_id):
    group = get_object_or_404(Group, pk=group_id)
    if request.user not in group.members.all():
        messages.error(request, 'You are not a member of this group.')
    elif group.owner == request.user:
        messages.error(request, 'You cannot leave a group you own. Please transfer ownership first.')
    else:
        group.members.remove(request.user)
        messages.success(request, f'Left {group.name}.')
    return HttpResponseClientRedirect(reverse('groups:index'))

@require_POST
def delete_group(request, group_id):
    group = get_object_or_404(Group, pk=group_id)
    if group.owner != request.user:
        return HttpResponseForbidden()
    group.delete()
    messages.success(request, 'Group deleted.')
    return HttpResponseClientRedirect(reverse('groups:index'))

battles/templates/battles/groups/create.html
{% extends "base.html" %}

{% block content %}
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        <form action="" method="post" hx-trigger="change" hx-get="{% url 'battles:create_group_preview' %}"
              class="flex flex-col gap-3 lg:col-span-2" hx-target="#battle-group-preview">
            {% csrf_token %}
            <div class="flex flex-row">
                <h1 class="text-3xl font-splatoon1">
                    {% block title %}
                        Create Battle Group
                    {% endblock %}
                </h1>
                <div class="grow"></div>
                <input type="submit" value="Create"
                       class="bg-pink-600 hover:bg-pink-700 text-purple-100 font-bold cursor-pointer rounded-lg p-2">
            </div>

            {% for battle in battles %}
                <div>
                    <input type="checkbox" id="battle-{{ battle.id }}" name="battle-{{ battle.id }}"
                           class="hidden peer">
                    <label class="flex flex-row gap-1 bg-gray-900 rounded-full px-2 py-1 peer-checked:outline outline-4 outline-white"
                           for="battle-{{ battle.id }}">
                        <div
                                class="rounded-full {% if battle.judgement == "WIN" %}bg-yellow-300{% else %}bg-gray-300{% endif %}
                                           text-gray-900 font-bold py-2 text-lg font-splatoon1 w-[7ch] text-center"
                        >
                            {{ battle.get_short_judgement_display|upper }}
                        </div>
                        <div class="flex flex-col shrink min-w-0">
                            <div class="text-sm whitespace-nowrap overflow-clip">{{ battle.vs_stage.name.string }}</div>
                            <div class="text-sm whitespace-nowrap overflow-clip">{{ battle.get_vs_rule_display }}</div>
                        </div>
                        <div class="grow"></div>
                        {% with player=battle.player team=battle.player.team %}
                            <div class="flex-none flex flex-row gap-1 px-4 justify-end rounded-full min-w-fit bg-black/50">
                                <span class="text-xl w-min whitespace-nowrap pt-1">{{ player.paint }}p</span>
                                <span class="text-lg w-min whitespace-nowrap pt-[2px]">
                                                {% if player.species == "OCTOLING" %}
                                                    {% include "battles/svg/octoling_splat.html" with color=team.color %}
                                                {% else %}
                                                    {% include "battles/svg/inkling_splat.html" with color=team.color %}
                                                {% endif %}
                                    x{{ player.kills|default_if_none:"--" }}
                                    {% if player.assists and player.assists != 0 %}
                                        <sub class="text-xs text-gray-300">
                                                                ({{ player.assists }})
                                                            </sub>
                                    {% endif %}
                                        </span>
                                <span class="text-lg w-min whitespace-nowrap pt-[2px]">
                                                    {% if player.species == "OCTOLING" %}
                                                        {% include "battles/svg/octoling_splatted.html" with color=team.next_team.color %}
                                                    {% else %}
                                                        {% include "battles/svg/inkling_splatted.html" with color=team.next_team.color %}
                                                    {% endif %}
                                    x{{ player.deaths|default_if_none:"--" }}
                                        </span>
                                <span class="text-lg w-min whitespace-nowrap">
                                    {% include "splatnet_assets/mask_image.html" with uploader=user object=player.weapon.special class="h-4 w-4 relative top-0" %}
                                    x{{ player.specials|default_if_none:"--" }}
                                        </span>
                            </div>
                        {% endwith %}
                    </label>
                </div>
            {% endfor %}
        </form>

        <div id="battle-group-preview" class="flex flex-col gap-4"></div>
    </div>
{% endblock %}

battles/templates/battles/groups/opengraph.html
{% extends "opengraph.html" %}
{% load static %}

{% block content %}
    <div class="w-[1200px] h-[630px] relative">
        {% if battle_group.creator.page_background and "page-backgrounds" in battle_group.creator.entitlements %}
            <img src="{{ battle_group.creator.page_background.url }}"
                 class="w-full h-full absolute top-0 left-0 object-cover brightness-[.35]">
        {% else %}
            <img src="{% static 'images/dark-bg.jpg' %}" class="w-full h-full absolute top-0 left-0">
        {% endif %}
        <div class="flex gap-16 justify-center items-center w-full h-full absolute top-0 left-0">
            <div class="flex flex-col items-center gap-6">
                <div class="card-mask h-fit w-fit bg-gray-500 rotate-2 bg-[url('../images/tapes-transparent.png')] bg-contain rounded-lg pb-3 px-6 pt-8 text-center">
                    <h1 class="font-splatoon1 text-4xl pb-8">Stats</h1>
                    <div class="flex justify-center items-center gap-6">
                        <div>
                            <div class="text-2xl">
                                Victory
                            </div>
                            <div class="text-4xl">
                                {{ win_count }}
                            </div>
                        </div>
                        <div>
                            <div class="text-2xl">
                                Defeat
                            </div>
                            <div class="text-4xl">
                                {{ lose_count }}
                            </div>
                        </div>
                    </div>

                    <div class="flex justify-center items-center gap-6 pt-4">
                        <div>
                            <div class="text-lg">
                                Win Rate
                            </div>
                            <div class="text-2xl">
                                {{ win_rate|floatformat:1 }}%
                            </div>
                        </div>
                    </div>
                </div>
                <div class="-rotate-1 scale-125">
                    {% include "includes/splashtag.html" with splashtag=splashtag %}
                </div>
            </div>

            <div class="flex flex-col items-center gap-6">
                {% for weapon in most_used_weapons %}
                    <div class="p-2 pt-6 card-mask h-fit w-fit bg-gray-600 rotate-3 odd:-rotate-3 bg-[url('/images/tapes-transparent.png')] bg-contain rounded-lg">
                        <div class="flex gap-1">
                            <img
                                    src="{{ weapon.flat_image.url }}"
                                    alt="{{ weapon.name.string }}"
                                    class="h-36"
                            >
                            <div class="flex flex-col gap-2">
                                {% include "splatnet_assets/mask_image.html" with object=weapon.special class="inline h-12 w-12 p-1 rounded bg-gray-900/90" uploader=battle_group.creator image_params="height=128&width=128" alt=weapon.special.name.string %}
                                {% include "splatnet_assets/mask_image.html" with object=weapon.sub class="inline h-12 w-12 p-1 rounded bg-gray-900/90" uploader=battle_group.creator image_params="height=128&width=128" alt=weapon.sub.name.string %}
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
        <span class="absolute bottom-2 right-2 text-xl opacity-50">splashcat.ink</span>
    </div>
{% endblock %}

battles/templates/battles/groups/preview.html
<div class="grid grid-cols-1 gap-4">
    {% for battle in battles %}
        {% include "users/includes/battle-card.html" with battle=battle %}
    {% endfor %}
</div>

battles/templates/battles/groups/view.html
{% extends "base.html" %}
{% load static %}

{% block opengraph_head %}
    <meta property="og:title" content="{{ battle_group.creator.display_name }}'s Shared Battle Group">

    <meta property="og:description" content="Splashcat is an award-winning service that records battle data for later analysis.">

    <meta name="twitter:card" content="summary_large_image">
    <meta property="og:image"
          content="https://cdn.splashcat.ink/image-render/battle-group/{{ battle_group.id }}/render.png?quality=100">
{% endblock %}

{% block content %}
    {% include "users/includes/page-background.html" with profile=battle_group.creator %}

    <h1 class="font-splatoon1 text-3xl pb-2">
        {% block title %}
            {{ battle_group.creator.display_name }}'s Shared Battle Group
        {% endblock %}

        <button class="share-button inline-block"
                data-url="https://splashcat.ink/battles/groups/{{ battle_group.id }}/?share"
                data-content-type="BattleGroup"
                data-share-type="webShare"
        >
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                 stroke="currentColor" class="w-8 h-8 inline">
                <path stroke-linecap="round" stroke-linejoin="round"
                      d="M9 8.25H7.5a2.25 2.25 0 00-2.25 2.25v9a2.25 2.25 0 002.25 2.25h9a2.25 2.25 0 002.25-2.25v-9a2.25 2.25 0 00-2.25-2.25H15m0-3l-3-3m0 0l-3 3m3-3V15"></path>
            </svg>
        </button>

        <button class="share-button inline-block"
                data-url="https://splashcat.ink/battles/groups/{{ battle_group.id }}/?share"
                data-content-type="BattleGroup"
                data-share-type="clipboard"
        >
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-8 h-8 inline">
                <path fill-rule="evenodd"
                      d="M19.902 4.098a3.75 3.75 0 00-5.304 0l-4.5 4.5a3.75 3.75 0 001.035 6.037.75.75 0 01-.646 1.353 5.25 5.25 0 01-1.449-8.45l4.5-4.5a5.25 5.25 0 117.424 7.424l-1.757 1.757a.75.75 0 11-1.06-1.06l1.757-1.757a3.75 3.75 0 000-5.304zm-7.389 4.267a.75.75 0 011-.353 5.25 5.25 0 011.449 8.45l-4.5 4.5a5.25 5.25 0 11-7.424-7.424l1.757-1.757a.75.75 0 111.06 1.06l-1.757 1.757a3.75 3.75 0 105.304 5.304l4.5-4.5a3.75 3.75 0 00-1.035-6.037.75.75 0 01-.354-1z"
                      clip-rule="evenodd"></path>
            </svg>
        </button>
    </h1>

    {% if battle_group.creator_id == user.id and user.has_splashcat_assistant %}
        <a href="{% url 'assistant:create_thread' 'battles' 'BattleGroup' battle_group.id %}"
           class="bg-purple-800 p-4 rounded w-fit max-h-fit block">Create Assistant Thread</a>
    {% endif %}

    <h2 class="font-splatoon1 text-xl">Creator</h2>
    {% include "users/includes/user-link.html" with user=battle_group.creator show_splashtag=True %}

    <h2 class="font-splatoon1 text-xl">Statistics</h2>
    <div class="flex flex-row flex-wrap divide-x-2 divide-gray-500 gap-y-2">
        <div class="px-4">
            <div class="text-lg">Victories</div>
            <div class="text-2xl">{{ win_count }}</div>
        </div>
        <div class="px-4">
            <div class="text-lg">Defeats</div>
            <div class="text-2xl">{{ lose_count }}</div>
        </div>
        <div class="px-4">
            <div class="text-lg">Win Rate</div>
            <div class="text-2xl">{{ win_rate|floatformat:1 }}%</div>
        </div>
    </div>

    <h2 class="font-splatoon1 text-xl">Battles</h2>
    <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4">
        {% for battle in battles %}
            {% include "users/includes/battle-card.html" with battle=battle %}
        {% endfor %}
    </div>
{% endblock %}