battles/urls.py
from django.urls import path

from battles.views import *

app_name = "battles"
urlpatterns = [
    path('api/upload/', upload_battle, name='upload_battle'),
    path('<int:battle_id>/', view_battle, name='view_battle'),
    path('<int:battle_id>/opengraph/', battle_opengraph, name='battle_opengraph'),
    path('redir/<str:uploader_username>/latest/', redirect_to_user_latest_battle,
         name='redirect_to_user_latest_battle'),
    path('redir/<str:uploader_username>/<str:splatnet_id>/', redirect_from_splatnet_id,
         name='redirect_from_splatnet_id'),
    path('api/<int:battle_id>/json/', get_battle_json, name='get_battle_json'),
    path('api/<str:splatnet_id>/exists/', check_if_battle_exists, name='check_battle_exists'),
    path('api/recent/', get_recent_battle_ids, name='get_recent_battle_ids'),
    path('htmx/latest/', get_latest_battles, name='htmx_latest_battles'),
    path('global-data-export/', global_data_export, name='global_data_export'),
    path('global-data-export/redirect/', redirect_global_data_export, name='redirect_global_data_export'),
    path('groups/<int:group_id>/', view_battle_group, name='view_battle_group'),
    path('groups/<int:group_id>/opengraph/', battle_group_opengraph, name='battle_group_opengraph'),
    path('groups/create/', create_battle_group, name='create_battle_group'),
    path('groups/create/htmx/preview/', create_group_preview, name='create_group_preview')
]

groups/urls.py
from django.urls import path

from groups.views import view_group, groups_index, group_admin, answer_join_request, invite_to_group, \
    answer_group_invite, request_join_group, join_group, leave_group, create_group, delete_group

app_name = "groups"
urlpatterns = [
    path("", groups_index, name="index"),
    path("<int:group_id>/", view_group, name="view_group"),
    path("<int:group_id>/admin/", group_admin, name="group_admin"),
    path("<int:group_id>/admin/delete/", delete_group, name="delete_group"),
    path("create/", create_group, name="create_group"),
    path("<int:group_id>/request/", request_join_group, name="request_join_group"),
    path("<int:group_id>/request/answer/", answer_join_request, name="answer_join_request"),
    path("<int:group_id>/invite/", invite_to_group, name="invite_to_group"),
    path("<int:group_id>/invite/answer/", answer_group_invite, name="answer_group_invite"),
    path("<int:group_id>/join/", join_group, name="join_group"),
    path("<int:group_id>/leave/", leave_group, name="leave_group"),
]

splashcat/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps import views
from django.urls import path, include
from django.views.decorators.csrf import csrf_exempt
from strawberry.django.views import AsyncGraphQLView

import users.views as users_views
from battles.sitemaps import BattlesSitemap, BattleGroupsSitemap
from django.conf import settings

from indexnow.views import indexnow_api_key
from splashcat.oidc_provider_settings import openid_auth
from splashcat.schema import schema
from splashcat.sitemaps import StaticViewSitemap
from splashcat.views import home, sponsor, uploaders_information, health_check, robots_txt, legal, ads_txt, about
from users.sitemaps import UsersSitemap

sitemaps = {
    'static': StaticViewSitemap,
    'users': UsersSitemap,
    'battles': BattlesSitemap,
    'battle-groups': BattleGroupsSitemap,
}

urlpatterns = [
    path('', home, name='home'),
    path('graphql', csrf_exempt(openid_auth(AsyncGraphQLView.as_view(schema=schema, graphql_ide="apollo-sandbox")))),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
    path('unicorn/', include('django_unicorn.urls')),
    path('users/', include('users.urls')),
    path('groups/', include('groups.urls')),
    path('battles/', include('battles.urls')),
    path('videos/', include('videos.urls')),
    path('search/', include('search.urls')),
    path('assistant/', include('assistant.urls')),
    path('embeds/', include('embed_images.urls')),
    path('sponsors/', include('sponsors.urls')),
    path('@<str:username>/', users_views.profile, name='profile'),
    path('@<str:username>.json', users_views.profile_json, name='profile_json'),
    path('@<str:username>/battles/', users_views.profile_battle_list, name='profile_battles_list'),
    path('@<str:username>/album/', users_views.profile_album, name='profile_album'),
    path('@<str:username>/followers/', users_views.profile_follows, {'view_type': 'followers'}, name='profile_followers'),
    path('@<str:username>/following/', users_views.profile_follows, {'view_type': 'following'}, name='profile_following'),
    path('set_user_timezone/', users_views.set_user_timezone, name='set_user_timezone'),
    path('follow/<str:username>/', users_views.follow_user, name='follow_user'),
    path('unfollow/<str:username>/', users_views.unfollow_user, name='unfollow_user'),
    path('notifications/mark-read/', users_views.mark_notifications_as_read, name='mark_notifications_as_read'),
    path('notifications/fetch/', users_views.get_notifications, name='fetch_notifications'),
    path('sponsor/', sponsor, name='sponsor'),
    path('legal/', legal, name='legal'),
    path('about/', about, name='about'),
    path('uploaders-information/', uploaders_information, name='uploaders_information'),
    path('health-check/', health_check, name='health_check'),
    path('i18n/', include('django.conf.urls.i18n')),
    path('openid/', include('oidc_provider.urls', namespace='oidc_provider')),
    path('robots.txt', robots_txt, name='robots_txt'),
    path('ads.txt', ads_txt, name='ads_txt'),
    path(f'{settings.INDEXNOW_API_KEY}.txt', indexnow_api_key, name='indexnow_api_key'),
    # path('silk/', include('silk.urls', namespace='silk')),
    path(
        "sitemap.xml",
        views.index,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.index",
    ),
    path(
        "sitemap-<section>.xml",
        views.sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # let web server handle this in production
    urlpatterns += static('api/schemas/', document_root=settings.BASE_DIR / 'battles/format_schemas/')

sponsors/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy

from sponsors.views import *

app_name = "sponsors"
urlpatterns = [
    path('create-checkout-session/<str:price_id>/', create_checkout_session, name='create_checkout_session'),
    path('webhook/', webhook_received, name='webhook_received'),
    path('portal/', redirect_to_portal, name='redirect_to_portal'),
    path('success/', checkout_success, name='checkout_success'),
]

users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy

from users.forms import AuthenticationForm
from users.views import *

app_name = "users"
urlpatterns = [
    path('coral/friendcode/qr/<str:username>/', profile_qr_code, name='profile_qr_code'),
    path('opengraph/<str:username>/user/', profile_opengraph, name='profile_opengraph'),
    path('api/github-sponsors-webhook/', github_sponsors_webhook, name='github_sponsors_webhook'),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="users/login.html", form_class=AuthenticationForm),
        name="login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(),
        name="logout",
    ),
    path(
        "password-reset/",
        auth_views.PasswordResetView.as_view(
            template_name="users/password_reset/form.html",
            email_template_name="users/password_reset/email_content.txt",
            subject_template_name="users/password_reset/email_subject.txt",
            success_url=reverse_lazy("users:password_reset_done"),

        ),
        name="password_reset",
    ),
    path("password-reset/done/",
         auth_views.PasswordResetDoneView.as_view(template_name="users/password_reset/done.html"),
         name='password_reset_done'),
    path("password-reset/confirm/<uidb64>/<token>/",
         auth_views.PasswordResetConfirmView.as_view(template_name="users/password_reset/confirm.html",
                                                     success_url=reverse_lazy("users:password_reset_complete")),
         name='password_reset_confirm'),
    path("password-reset/complete/",
         auth_views.PasswordResetCompleteView.as_view(template_name="users/password_reset/complete.html"),
         name='password_reset_complete'),
    path(
        "register/",
        register,
        name="register",
    ),
    path(
        "settings/",
        user_settings,
        name="settings",
    ),
    path(
        "settings/request-data-export/",
        request_data_export,
        name="request_data_export",
    ),
    path('github/link/',
         link_github_account,
         name='link_github_account'),
    path('github/link/callback/',
         link_github_account_callback,
         name='link_github_account_callback'),
    path('api-keys/create/',
         create_api_key,
         name='create_api_key'),
    path('api-keys/<str:key>/delete/',
         delete_api_key,
         name='delete_api_key'),
    path('verify-email/<int:user_id>/<str:token>/',
         verify_email,
         name='verify_email'),
    path('verify-email/resend/',
         resend_verification_email,
         name='resend_verification_email'),
]

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm as DjangoAuthenticationForm
from django.utils.translation import gettext_lazy as _

from users.models import User


class ImageWidget(forms.widgets.ClearableFileInput):
    template_name = "users/widgets/image.html"


class AccountSettingsForm(forms.ModelForm):
    class Meta:
        model = User
        fields = (
            "display_name",
            "profile_picture",
            "profile_cover",
            "page_background",
            "saved_favorite_color",
            "x_battle_division",
            "preferred_pronouns",
            "coral_friend_url",
            "show_player_names",
        )
        labels = {
            "saved_favorite_color": _("Favorite Color"),
        }
        help_texts = {
            "saved_favorite_color": _("Shown when you sponsor Splashcat."),
        }
        widgets = {
            "profile_cover": ImageWidget,
            "page_background": ImageWidget,
        }

    profile_picture = forms.ImageField(
        label=_("Profile Picture"),
        required=True,
        widget=ImageWidget()
    )

    # override the attributes on the preferred_pronouns field to prevent autocomplete
    preferred_pronouns = forms.CharField(
        required=False,
        widget=forms.TextInput(
            attrs={
                "autocomplete": "off",
                "autocorrect": "off",
            }
        )
    )

    coral_friend_url = forms.URLField(
        required=False,
        error_messages={
            'invalid': _("Enter a valid Nintendo Switch Friend URL from the Nintendo Switch Online app."),
        },
        widget=forms.URLInput(
            attrs={
                'class': '!w-full',
            }
        )
    )


class RegisterForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = UserCreationForm.Meta.fields + (
            "display_name",
            "email",
        )


class AuthenticationForm(DjangoAuthenticationForm):
    error_messages = DjangoAuthenticationForm.error_messages | {
        'email_not_verified': _('Your email address is not verified. Please check your email for a verification link.'),
    }

    def clean(self):
        username = self.cleaned_data.get("username")
        if username is not None:
            try:
                user = User.objects.get(username=username)
                if user:
                    if not user.verified_email:
                        raise forms.ValidationError(
                            self.error_messages['email_not_verified'],
                            code='email_not_verified',
                        )
            except User.DoesNotExist:
                pass
        super().clean()

    def confirm_login_allowed(self, user):
        super().confirm_login_allowed(user)
        if not user.verified_email:
            raise forms.ValidationError(
                self.error_messages['email_not_verified'],
                code='email_not_verified',
            )


class ResendVerificationEmailForm(forms.Form):
    email = forms.EmailField(label=_("Email address"), max_length=254)

    def clean_email(self):
        email = self.cleaned_data.get("email")
        if email is not None:
            user = User.objects.get(email=email)
            if user:
                if user.verified_email:
                    raise forms.ValidationError(
                        _("This email address is already verified."),
                        code='email_already_verified',
                    )
        return email

    def send_email(self):
        email = self.cleaned_data.get("email")
        if email is not None:
            user = User.objects.get(email=email)
            if user:
                user.send_verification_email()

users/templates/users/login.html
{% extends "base.html" %}

{% block title %}Login{% endblock %}

{% block content %}

    <h1 class="font-splatoon1 text-3xl">Login</h1>

    {% if next %}
        {% if user.is_authenticated %}
            <p>Your account doesn't have access to this page. To proceed,
                please login with an account that has access.</p>
        {% else %}
            <p>Please login to see this page.</p>
        {% endif %}
    {% endif %}

    <form method="post" action="{% url 'users:login' %}" class="form-css">
        {% csrf_token %}
        {{ form.as_div }}

        <input type="submit" value="Login">
        <input type="hidden" name="next" value="{{ next }}">
    </form>

    {# Assumes you set up the password_reset view in your URLconf #}
    <p><a href="{% url 'users:password_reset' %}">Lost password?</a></p>
    <p><a href="{% url 'users:resend_verification_email' %}">Resend Verification Email</a></p>

{% endblock %}

users/templates/users/password_change.html
{% extends "base.html" %}

{% block title %}Change Password{% endblock %}

{% block content %}

    <h1 class="font-splatoon1 text-3xl">Change Password</h1>

    {% if form.errors %}
        <p>Your old password was entered incorrectly. Please enter it again.</p>
    {% endif %}

    <form method="post" action="{% url 'password_change' %}" class="form-css">
        {% csrf_token %}
        {{ form.as_div }}

        <input type="submit" value="Change">
        <input type="hidden" name="next" value="{{ next }}">
    </form>

{% endblock %}

users/templates/users/profile_album.html
{% extends "base.html" %}

{% load static %}

{% block title %}
    {{ profile_user.display_name }}'s Album
{% endblock %}

{% block opengraph_head %}
    <meta property="og:title" content="{{ profile_user.display_name }}'s Album'">

    <meta property="og:description" content="Splashcat is an award-winning service that records battle data for later analysis.">

    <meta name="twitter:card" content="summary_large_image">
    <meta property="og:image"
          content="https://cdn.splashcat.ink/image-render/user/{{ profile_user.username }}/render.png?quality=100&cache_key={{ request.GET.cache }}">
{% endblock %}

{% block content %}
    {% include "users/includes/page-background.html" with profile=profile_user %}

    <div class="flex flex-col md:flex-row gap-4 overflow-x-clip">
        <div class="basis-2/5 xl:basis-1/4 flex flex-col gap-2">
            {% include 'users/profile_sidebar.html' with profile=profile_user %}
        
            <button class="share-button inline w-fit"
                    data-url="https://splashcat.ink/@{{ profile_user.username }}/album/?share&cache={{ profile_user.album_images.count }}"
                    data-content-type="ProfileAlbumImages"
                    data-share-type="webShare"
            >
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                     stroke="currentColor" class="w-8 h-8 inline">
                    <path stroke-linecap="round" stroke-linejoin="round"
                          d="M9 8.25H7.5a2.25 2.25 0 00-2.25 2.25v9a2.25 2.25 0 002.25 2.25h9a2.25 2.25 0 002.25-2.25v-9a2.25 2.25 0 00-2.25-2.25H15m0-3l-3-3m0 0l-3 3m3-3V15"></path>
                </svg>
            </button>

            <button class="share-button inline w-fit"
                    data-url="https://splashcat.ink/@{{ profile_user.username }}/album/?share&cache={{ profile_user.album_images.count }}"
                    data-content-type="ProfileAlbumImages"
                    data-share-type="clipboard"
            >
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-8 h-8 inline">
                    <path fill-rule="evenodd"
                          d="M19.902 4.098a3.75 3.75 0 00-5.304 0l-4.5 4.5a3.75 3.75 0 001.035 6.037.75.75 0 01-.646 1.353 5.25 5.25 0 01-1.449-8.45l4.5-4.5a5.25 5.25 0 117.424 7.424l-1.757 1.757a.75.75 0 11-1.06-1.06l1.757-1.757a3.75 3.75 0 000-5.304zm-7.389 4.267a.75.75 0 011-.353 5.25 5.25 0 011.449 8.45l-4.5 4.5a5.25 5.25 0 11-7.424-7.424l1.757-1.757a.75.75 0 111.06 1.06l-1.757 1.757a3.75 3.75 0 105.304 5.304l4.5-4.5a3.75 3.75 0 00-1.035-6.037.75.75 0 01-.354-1z"
                          clip-rule="evenodd"></path>
                </svg>
            </button>
            {% with groups=profile_user.get_groups %}
                {% if groups|length > 0 %}
                    <h2 class="text-xl font-splatoon1">Groups</h2>
                    {% for group in groups %}
                        {% include 'groups/includes/card.html' with group=group %}
                    {% endfor %}
                {% endif %}
            {% endwith %}
        </div>

        <div class="flex grow flex-col gap-2">
            <div class="flex flex-ror gap-4">
                <h2 class="text-3xl font-splatoon1">Album</h2>
            </div>

            {% include "includes/nuxt_iframe.html" with path="/@"|add:profile_user.username|add:"/album" %}
        </div>
    </div>
{% endblock %}

users/templates/users/register.html
{% extends "base.html" %}

{% block title %}Register{% endblock %}

{% block content %}

    <h1 class="font-splatoon1 text-3xl">Register</h1>

    <form method="post" action="{% url 'users:register' %}" class="form-css plausible-event-name=Register">
        {% csrf_token %}
        {{ form.as_div }}

        <div class="h-captcha" data-sitekey="f04325b9-66a6-4fda-8293-7ea4c25dcfee" data-theme="dark"></div>
        <script src="https://js.hcaptcha.com/1/api.js" async defer></script>

        <input type="submit" value="Register">
        <input type="hidden" name="next" value="{{ next }}">
    </form>

{% endblock %}

users/templates/users/resend_verification_email.html
{% extends "base.html" %}

{% block content %}
    <h1 class="text-3xl font-splatoon1">{% block title %}
        Resend Verification Email
    {% endblock %}</h1>

    <form method="post" action="{% url 'users:resend_verification_email' %}" class="form-css">
        {% csrf_token %}
        {{ form.as_div }}

        <input type="submit" value="Resend Email">
    </form>
{% endblock %}

users/templates/users/settings.html
{% extends "base.html" %}

{% block title %}
    Settings
{% endblock %}

{% block content %}
    <div class="flex flex-row gap-4">
        <h1 class="text-3xl font-splatoon1 mb-2">
            Settings
        </h1>
        {% if user.stripe_customer_id %}
            <form action="{% url 'sponsors:redirect_to_portal' %}" method="post">
                {% csrf_token %}
                <input type="submit" value="Stripe Customer Portal"
                       class="p-4 bg-pink-600 hover:bg-pink-700 rounded plausible-event-name=Stripe+Customer+Portal">
            </form>
        {% endif %}
    </div>

    <div class="grid gap-4 grid-cols-1 md:grid-cols-2">
        <div>
            {{ form.non_field_errors }}

            <form class="form-css form-div-cards" method="post" action="{% url "users:settings" %}"
                  enctype="multipart/form-data">
                {% csrf_token %}

                <div>
                    {{ form.display_name.errors }}
                    <label class="text-xl pt-2" for="{{ form.display_name.id_for_label }}">Display Name</label>
                    {{ form.display_name }}
                </div>

                <div>
                    {{ form.profile_picture.errors }}
                    <label class="text-xl pt-2" for="{{ form.profile_picture.id_for_label }}">Profile Picture</label>
                    {{ form.profile_picture }}
                </div>

                <div>
                    {{ form.profile_cover.errors }}
                    <label class="text-xl pt-2" for="{{ form.profile_cover.id_for_label }}">Profile Cover</label>
                    {{ form.profile_cover }}
                </div>

                <div>
                    {{ form.page_background.errors }}
                    <label class="text-xl" for="{{ form.page_background.id_for_label }}">Page Background</label>
                    <p class="text-lg max-w-sm">
                        Shown in the background of your profile and on battles. Note that backgrounds will be darkened
                        when shown.
                    </p>
                    {{ form.page_background }}
                    {% if not "page-backgrounds" in user.entitlements %}
                        <div class="w-72"></div>
                        <div class="w-full h-full flex flex-col absolute left-0 top-0 items-center bg-black/60 pt-10 p-6">
                            <a class="text-center text-gray-200 text-lg h-full" href="{% url 'sponsor' %}">
                                Become a sponsor to customize your page background.
                            </a>
                        </div>
                    {% endif %}
                </div>

                <div>
                    {{ form.saved_favorite_color.errors }}
                    <label class="text-xl" for="{{ form.saved_favorite_color.id_for_label }}">Favorite Color</label>
                    <p class="text-lg max-w-sm">
                        Sub and special weapon icons will use this color on your profile and elsewhere on Splashcat.
                    </p>
                    {{ form.saved_favorite_color }}
                    {% if not "favorite-color" in user.entitlements %}
                        <div class="w-72"></div>
                        <div class="w-full h-full flex flex-col absolute left-0 top-0 items-center bg-black/60 pt-10 p-6">
                            <a class="text-center text-gray-200 text-lg h-full" href="{% url 'sponsor' %}">
                                Become a sponsor to change your favorite color.
                            </a>
                        </div>
                    {% endif %}
                </div>

                <div>
                    {{ form.x_battle_division.errors }}
                    <label class="text-xl" for="{{ form.x_battle_division.id_for_label }}">X Battle Division</label>
                    <p class="text-lg">
                        The Takoroka Division is for players from Japan, Hong Kong, South Korea, Australia, and New
                        Zealand.</p>
                    <p class="text-lg">
                        The Tentatek Division is for players from the Americas and Europe.
                    </p>
                    {{ form.x_battle_division }}
                </div>

                <div>
                    <div class="grid grid-cols-2">
                        <div class="col-span-1">
                            {{ form.coral_friend_url.errors }}
                            <label class="text-xl" for="{{ form.coral_friend_url.id_for_label }}">Nintendo Switch Friend
                                URL</label>
                            <p>
                                Get this link from the
                                <a href="https://lounge.nintendo.com/" class="underline text-blue-500">
                                    Nintendo Switch Online app
                                </a>. This link and your friend code are shown on your profile.
                            </p>
                        </div>
                        <video src="https://vz-bf1651f8-2e8.b-cdn.net/56c97329-e82d-42e8-912f-50de2d57e521/play_720p.mp4"
                               autoplay muted loop playsinline
                               class="max-h-64 col-span-1 rounded-xl w-min mx-auto shadow-2xl"></video>
                    </div>
                    {{ form.coral_friend_url }}
                </div>

                <div>
                    {{ form.show_player_names.errors }}
                    <label class="text-xl" for="{{ form.show_player_names.id_for_label }}">Show Player Names on
                        Battles</label>
                    <p>Disabling this will hide the names of all other players in all of your battles. Your own details
                        will always be displayed.</p>
                    {{ form.show_player_names }}
                </div>

                <div>
                    {{ form.preferred_pronouns.errors }}
                    <label class="text-xl" for="{{ form.preferred_pronouns.id_for_label }}">Preferred Pronouns</label>
                    <p>Used for AI Generated Battle Descriptions and shown on your profile.</p>
                    {{ form.preferred_pronouns }}
                </div>

                <div>
                    {% for error in formset.errors %}
                        {{ error }}
                    {% endfor %}
                    <label class="text-xl">Profile URLs</label>
                    <p>Link to accounts on other platforms. Links will have <code class="font-mono">`rel="me"`</code>
                        added.</p>
                    {{ formset.as_div }}
                </div>

                <input type="submit" value="Update">
            </form>
        </div>

        <div>
            <div class="form-div-cards">
                <div>
                    <h1 class="text-xl font-splatoon1">GitHub Sponsors</h1>
                    <p>
                        Sponsors on GitHub can link their GitHub account to Splashcat to receive special features.
                    </p>

                    {% if user.github_link.github_id %}
                        <div class="p-2 my-2 rounded backdrop-blur-lg bg-slate-900/40">
                            Your Splashcat account is linked to
                            <a href="https://github.com/{{ user.github_link.github_username }}"
                               class="underline text-blue-500">
                                @{{ user.github_link.github_username }}
                            </a>
                            on GitHub.
                        </div>
                    {% endif %}

                    <form action="{% url 'users:link_github_account' %}" method="post"
                          class="form-css flex flex-row gap-4 pt-1">
                        {% csrf_token %}
                        <input
                                type="submit"
                                value="{% if user.github_link.github_id %}Relink GitHub Account{% else %}Link GitHub Account{% endif %}"
                        >

                        {% if user.github_link.github_id %}
                            <button name="is_refresh" value="true" class="p-4 rounded bg-pink-600 hover:bg-pink-700"
                                    _="on click remove .animate-none from the <svg/> in me"
                            >
                                {% include "splatnet_assets/squid_spinner.html" with class="h-6 w-6 inline-block animate-[spin_2s_linear_infinite] animate-none" %}
                                Refresh Sponsorship
                            </button>
                        {% endif %}
                    </form>
                </div>

                <div>
                    <h1 class="text-xl font-splatoon1 pt-2">API Keys</h1>
                    <p>
                        Create API keys to upload data to Splashcat.
                    </p>
                    <form action="{% url 'users:create_api_key' %}" method="post" class="form-css">
                        {% csrf_token %}
                        <input type="text" name="note" placeholder="Note">
                        <input type="submit" value="Create API Key">
                    </form>

                    {% with api_keys=user.api_keys.all %}
                        {% if api_keys %}
                            <table class="w-max table-auto border-collapse">
                                <thead>
                                <tr>
                                    <th class="border border-slate-200 p-1">Key</th>
                                    <th class="border border-slate-200 p-1">Note</th>
                                    <th class="border border-slate-200 p-1">Created</th>
                                    <th class="border border-slate-200 p-1">Delete</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for api_key in api_keys %}
                                    <tr>
                                        <td class="border border-slate-200 p-1 font-mono">{{ api_key.key }}</td>
                                        <td class="border border-slate-200 p-1">{{ api_key.note }}</td>
                                        <td class="border border-slate-200 p-1">{{ api_key.created }}</td>
                                        <td class="border border-slate-200 p-1">
                                            <form action="{% url 'users:delete_api_key' api_key.key %}" method="post">
                                                {% csrf_token %}
                                                <input type="submit" value="❌">
                                            </form>
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        {% endif %}
                    {% endwith %}
                </div>

                <div>
                    <h1 class="text-xl font-splatoon1 pt-2">Request Data Export</h1>
                    <p>
                        Request a copy of your data from Splashcat.
                    </p>

                    <form action="{% url 'users:request_data_export' %}" method="post" class="form-css pt-1">
                        {% csrf_token %}
                        <input type="submit" value="Request Data Export">
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}